// Real PTY terminal — spawns $SHELL in a pseudo-terminal, streams I/O via Tauri events.
// Frontend uses xterm.js; backend uses portable-pty for cross-platform PTY creation.

use portable_pty::{native_pty_system, CommandBuilder, PtySize};
use std::io::{Read, Write};
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc, Mutex,
};
use tauri::Emitter;

pub struct PtySession {
    writer: Box<dyn Write + Send>,
    master: Box<dyn portable_pty::MasterPty + Send>,
    child:  Box<dyn portable_pty::Child  + Send + Sync>,
    stop:   Arc<AtomicBool>,
}

pub type PtyHandle = Arc<Mutex<Option<PtySession>>>;

pub fn new_handle() -> PtyHandle {
    Arc::new(Mutex::new(None))
}

/// Resolve the one workspace root used by the shell and every generated tool.
///
/// The frontend supplies a path, never a display name. Resolve it once in the
/// backend, fail closed if it is not a directory, then pass this exact value as
/// both the process cwd and `SAIENT_WORKSPACE`. Nothing downstream is allowed to
/// rebuild a path from project metadata.
fn canonical_workspace(cwd: &str) -> Result<std::path::PathBuf, String> {
    if cwd.trim().is_empty() {
        return Err("terminal workspace path is empty".to_string());
    }
    crate::paths::canonical_existing_dir(
        std::path::Path::new(cwd), "terminal workspace")
}

fn kill_session(mut session: PtySession) {
    session.stop.store(true, Ordering::Relaxed);
    let _ = session.child.kill();
    // Drop order: writer, master, child, stop — killing child closes the slave PTY,
    // which causes the reader thread's read() to return EIO and exit.
}

// ── Saient terminal init ───────────────────────────────────────────────────────
// Two generated files written to Saient's managed config dir on each PTY spawn:
//   saient.bashrc  — sourced via `bash --rcfile`; defines the `saient` command and
//                   prints a greeting. Re-sources ~/.bashrc so the user's env works.
//   saient_cli.py  — the Saient agent TUI. Pure-stdlib Python: renders the ASCII
//                   splash, finds the running tinyq4 server, streams chat over its
//                   OpenAI-compatible SSE endpoint. No external deps, no opencode.

const SAIENT_BASHRC: &str = r##"# Saient terminal init — generated by Saient. Safe to edit; regenerated on app launch.
unset npm_config_prefix 2>/dev/null
[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# Launch the Saient agent TUI (talks to the local tinyq4 server).
saient() {
  python3 "$SAIENT_CONFIG_DIR/saient_cli.py" "$@"
}

# Greeting shown when the terminal opens.
printf '\n\033[38;2;108;142;245msaient\033[0m \033[2m›\033[0m type \033[1msaient\033[0m \033[2mto launch the agent\033[0m\n\n'

# To boot straight into the agent every time the terminal opens, uncomment:
# saient
"##;

const SAIENT_CLI_PY: &str = r####"#!/usr/bin/env python3
# Saient — local coding agent TUI. Generated by Saient.
# Talks to the tinyq4 OpenAI-compatible server the app already manages, and can
# act on the workspace via a ReAct-style tool loop (read/ls/write/edit/bash).
# Pure standard library: no pip installs required.
import sys, os, json, queue, re, signal, shutil, subprocess, tempfile, threading, urllib.request, platform
from pathlib import Path

A = "\033[38;2;108;142;245m"   # accent blue
D = "\033[2m"                  # dim
B = "\033[1m"                  # bold
G = "\033[38;2;0;214;143m"     # green
R = "\033[38;2;248;113;113m"   # red
Y = "\033[38;2;245;166;35m"    # amber
X = "\033[0m"                  # reset

BANNER = r"""
   ███████╗ █████╗ ██╗███████╗███╗   ██╗████████╗
   ██╔════╝██╔══██╗██║██╔════╝████╗  ██║╚══██╔══╝
   ███████╗███████║██║█████╗  ██╔██╗ ██║   ██║
   ╚════██║██╔══██║██║██╔══╝  ██║╚██╗██║   ██║
   ███████║██║  ██║██║███████╗██║ ╚████║   ██║
   ╚══════╝╚═╝  ╚═╝╚═╝╚══════╝╚═╝  ╚═══╝   ╚═╝
"""

PORTS = [18081, 18082, 33115, 18080]
WORKSPACE_ENV = "SAIENT_WORKSPACE"
if not os.environ.get(WORKSPACE_ENV):
    raise RuntimeError("SAIENT_WORKSPACE is missing; refusing an unbound terminal root")
WORKSPACE = os.path.realpath(os.environ[WORKSPACE_ENV])
if not os.path.isdir(WORKSPACE):
    raise RuntimeError("SAIENT_WORKSPACE is not a directory: " + WORKSPACE)
TEMP_ROOTS = []         # only directories created by the tempdir tool
INPUT_QUEUE = queue.Queue()
INPUT_READER_STARTED = False
MAX_STEPS = 25          # tool-loop iterations per user turn
MAX_OUT   = 4000        # max chars of a tool result fed back to the model

RUNTIME_DIR = os.environ.get("SAIENT_RUNTIME_DIR", "")
if RUNTIME_DIR and RUNTIME_DIR not in sys.path:
    sys.path.insert(0, RUNTIME_DIR)

BINDING_ERROR = None
BINDING_MANIFEST = None
try:
    import binding_bridge as SAIENT_BINDING
    import desktop_bridge as SAIENT_BRIDGE
    import orchestrator as SAIENT_RUNTIME
    from expression import ModelExpresser
except Exception as exc:
    SAIENT_BINDING = None
    SAIENT_BRIDGE = None
    SAIENT_RUNTIME = None
    ModelExpresser = None
    BINDING_ERROR = "%s: %s" % (type(exc).__name__, exc)

def ensure_formal_binding(port):
    """Prove this exact host/runtime pair before any agent inference."""
    global BINDING_ERROR, BINDING_MANIFEST
    if BINDING_MANIFEST is not None:
        return True
    if BINDING_ERROR:
        return False
    try:
        config = Path(os.environ.get("SAIENT_CONFIG_DIR", ".")).expanduser().resolve()
        manifest, _ = SAIENT_BINDING.ensure_binding(
            "http://127.0.0.1:%d" % port, config / "bindings")
        BINDING_MANIFEST = manifest
        return True
    except Exception as exc:
        BINDING_ERROR = "%s: %s" % (type(exc).__name__, exc)
        return False

SYSTEM = """You are the proposal host inside Saient's local terminal. You are not
Saient and you are not the user-facing speaker. You may propose one tool call at
a time; Saient's rule policy and conscience decide whether it runs, and the
controller verifies the result. You work inside this directory:
__WS__

Operating system: __OS__. When using the bash tool, use commands native to this OS — on Windows use PowerShell/cmd (dir, type, copy, del, findstr, Remove-Item), NEVER Linux commands (ls, cat, rm, grep, touch).

You can ACT using tools. To use a tool, reply with ONE fenced json block and nothing else:
```json
{"name": "read", "path": "src/main.py"}
```

Tools:
- env   {"name":"env"}                                         inspect the actual local environment
- tempdir {"name":"tempdir","prefix":"diagnostic"}          create an isolated temporary workspace as @temp
- read  {"name":"read","path":"<file>"}                          read a file
- ls    {"name":"ls","path":"<dir>"}                             list a directory ("." = current)
- write {"name":"write","path":"<file>","content":"<text>"}      create or overwrite a file
- edit  {"name":"edit","path":"<file>","old":"<exact>","new":"<replacement>"}  replace text once
- bash  {"name":"bash","command":"<shell command>"}              run a command in the workspace

Workflow:
- Emit a SINGLE tool block to gather info or make a change. Planning prose is optional and is not shown to the user.
- You will receive the tool result, then continue with the next step.
- Use 'edit' for existing files (include enough surrounding text so 'old' is unique). Use 'write' for new files.
- Paths are relative to the workspace. Managed temporary paths use the stable
  `@temp` handle; absolute paths are never accepted from the proposal host.
- For a temporary diagnostic workspace, call `tempdir`; then use `@temp` or `@temp/file.txt` in every later tool. The host receives only this stable handle, never the random absolute path. Do not invent or copy an absolute temp path and do not create the workspace in the project.
- Preserve exact strings in tool arguments. Never add spaces beside `/`, `.`, `_`, `@`, or `-`, and never HTML-escape shell operators such as `&&`.
- A command written in prose or a `bash` fence is not executed. Every action must be the single fenced JSON tool block shown above.
- Do NOT write closing or sign-off lines while you are still working. No "feel
  free to try these commands", no "let me know if you need anything else", no
  "hope this helps". If a tool block follows, the turn is not over, and a
  farewell in the middle of it tells the person you have finished when you have
  not.
- When the task is fully complete, reply with a short factual draft and NO json block. The controller passes that draft and the verified tool journal to Saient's expression stage; this host never speaks as Saient directly.
"""

def discover_ports():
    # The app spawns tinyq4 on a dynamically-allocated free port, so static probe
    # ports aren't enough. Prefer the port the app hands us via env; then (Linux)
    # scan /proc for a `tinyq4 ... --server <port>` process; then fall back to known.
    found = []
    env_port = os.environ.get("SAIENT_SERVER_PORT")
    if env_port:
        try: found.append(int(env_port))
        except ValueError: pass
    try:
        for pid in os.listdir("/proc"):
            if not pid.isdigit():
                continue
            try:
                with open("/proc/%s/cmdline" % pid, "rb") as f:
                    args = [a.decode("utf-8", "replace") for a in f.read().split(b"\x00") if a]
            except Exception:
                continue
            if not args or not any("tinyq4" in a for a in args):
                continue
            for i, a in enumerate(args):
                if a == "--server" and i + 1 < len(args):
                    try:
                        found.append(int(args[i + 1]))
                    except ValueError:
                        pass
    except Exception:
        pass
    seen, ordered = set(), []
    for p in found + PORTS:
        if p not in seen:
            seen.add(p); ordered.append(p)
    return ordered

def find_server():
    for p in discover_ports():
        try:
            r = urllib.request.urlopen("http://127.0.0.1:%d/health" % p, timeout=0.4)
            if r.status == 200:
                model = "local model"
                try:
                    m = json.load(urllib.request.urlopen("http://127.0.0.1:%d/v1/models" % p, timeout=0.4))
                    model = m["data"][0]["id"]
                except Exception:
                    pass
                return p, model
        except Exception:
            continue
    return None, None

def stream(port, messages):
    body = json.dumps({"messages": messages, "stream": True,
                       "max_tokens": 2048, "temperature": 0.3}).encode()
    req = urllib.request.Request(
        "http://127.0.0.1:%d/v1/chat/completions" % port,
        data=body, headers={"Content-Type": "application/json"})
    out = ""
    with urllib.request.urlopen(req) as resp:
        for raw in resp:
            line = raw.decode("utf-8", "replace").strip()
            if not line.startswith("data:"):
                continue
            payload = line[5:].strip()
            if payload == "[DONE]":
                break
            try:
                delta = json.loads(payload)["choices"][0]["delta"]
            except Exception:
                continue
            think = delta.get("reasoning_content")
            content = delta.get("content")
            if content:
                out += content
    return out

# ── Tools ──────────────────────────────────────────────────────────────────
def safe_path(p):
    p = str(p)
    if p == "@temp" or p.startswith("@temp/"):
        if not TEMP_ROOTS:
            raise ValueError("@temp is unavailable until the tempdir tool succeeds")
        suffix = p[len("@temp"):].lstrip("/\\")
        p = os.path.join(TEMP_ROOTS[-1], suffix)
    full = os.path.realpath(os.path.join(WORKSPACE, p))
    if full == WORKSPACE or full.startswith(WORKSPACE + os.sep):
        return full
    for root in TEMP_ROOTS:
        if full == root or full.startswith(root + os.sep):
            return full
    raise ValueError("path is outside the workspace and managed temporary directories: %s" % p)

def in_temp(path):
    full = os.path.realpath(path)
    return any(full == root or full.startswith(root + os.sep) for root in TEMP_ROOTS)

def trunc(s):
    return s if len(s) <= MAX_OUT else s[:MAX_OUT] + ("\n…[truncated %d chars]" % (len(s) - MAX_OUT))

FENCE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.S)

def extract_tool(text):
    cand = None
    m = FENCE.search(text)
    if m:
        cand = m.group(1)
    else:
        i = text.find('{"name"')
        if i == -1:
            i = text.find('{ "name"')
        if i != -1:
            depth = 0
            for j in range(i, len(text)):
                if text[j] == "{": depth += 1
                elif text[j] == "}":
                    depth -= 1
                    if depth == 0:
                        cand = text[i:j+1]; break
    if not cand:
        return None
    try:
        obj = json.loads(cand)
    except Exception:
        return None
    return obj if isinstance(obj, dict) and "name" in obj else None

def _stdin_reader():
    while True:
        line = sys.stdin.readline()
        if line == "":
            INPUT_QUEUE.put(None)
            return
        INPUT_QUEUE.put(line.rstrip("\r\n"))

def read_line(prompt):
    global INPUT_READER_STARTED
    if not INPUT_READER_STARTED:
        threading.Thread(target=_stdin_reader, daemon=True).start()
        INPUT_READER_STARTED = True
    print(prompt, end="", flush=True)
    line = INPUT_QUEUE.get()
    if line is None:
        raise EOFError
    return line

def confirm(summary, yolo):
    if yolo:
        return True
    try:
        ans = read_line("   %sallow%s %s %s[y/N]%s " % (Y, X, summary, D, X)).strip().lower()
    except (EOFError, KeyboardInterrupt):
        print(); return False
    return ans in ("y", "yes")

BASH_TIMEOUT = 600   # seconds — long enough for npm/expo/pip installs

# Tools return (label, result_for_model, ok, shown). When shown is True the tool
# already printed its own ⚙ header + output (used by bash, which streams live).
def run_tool(obj, yolo):
    name = obj.get("name", "")
    try:
        if name == "env":
            usage = shutil.disk_usage(WORKSPACE)
            facts = [
                "cwd=" + WORKSPACE,
                "os=" + platform.platform(),
                "machine=" + platform.machine(),
                "python=" + platform.python_version(),
                "cpu_count=" + str(os.cpu_count() or "unknown"),
                "workspace_entries=" + str(len(os.listdir(WORKSPACE))),
                "workspace_free_bytes=" + str(usage.free),
            ]
            return "env", "\n".join(facts), True, False
        if name == "tempdir":
            prefix = re.sub(r"[^A-Za-z0-9_-]+", "-", str(obj.get("prefix", "work"))).strip("-")[:32] or "work"
            root = os.path.realpath(tempfile.mkdtemp(prefix="saient-%s-" % prefix))
            TEMP_ROOTS.append(root)
            print("\n   %s⚙%s %stempdir%s" % (G, X, B, X))
            show_result("handle=@temp\nresolved_path=" + root)
            # The absolute random path is user-visible evidence, but it never
            # enters the host prompt. @temp is the controller-owned stable name.
            return "tempdir", "handle=@temp", True, True
        if name == "read":
            with open(safe_path(obj["path"]), "r", errors="replace") as f:
                return "read " + obj["path"], trunc(f.read()), True, False
        if name == "ls":
            d = obj.get("path", ".")
            p = safe_path(d)
            items = sorted(os.listdir(p))
            out = "\n".join((i + "/") if os.path.isdir(os.path.join(p, i)) else i for i in items)
            return "ls " + d, (out or "(empty)"), True, False
        if name == "write":
            rel = obj["path"]; content = obj.get("content", "")
            p = safe_path(rel)
            if not in_temp(p) and not confirm("write %s%s%s (%d bytes)" % (B, rel, X, len(content)), yolo):
                return "write " + rel, "denied by user", False, False
            os.makedirs(os.path.dirname(p) or ".", exist_ok=True)
            with open(p, "w") as f:
                f.write(content)
            return "write " + rel, "wrote %d bytes" % len(content), True, False
        if name == "edit":
            rel = obj["path"]; old = obj.get("old", ""); new = obj.get("new", "")
            p = safe_path(rel)
            if not in_temp(p) and not confirm("edit %s%s%s" % (B, rel, X), yolo):
                return "edit " + rel, "denied by user", False, False
            with open(p, "r", errors="replace") as f:
                src = f.read()
            n = src.count(old)
            if old == "" or n == 0:
                return "edit " + rel, "old text not found — adjust and retry", False, False
            if n > 1:
                return "edit " + rel, "old text appears %d times — add more context to make it unique" % n, False, False
            with open(p, "w") as f:
                f.write(src.replace(old, new, 1))
            return "edit " + rel, "replaced 1 occurrence", True, False
        if name == "bash":
            cmd = obj.get("command", "")
            if not confirm("run: %s%s%s" % (B, cmd, X), yolo):
                return "bash", "denied by user", False, False
            # Stream output live so long installs (npm/expo/pip) show progress,
            # with a watchdog that kills runaway commands after BASH_TIMEOUT.
            print("\n   %s⚙%s %sbash %s%s" % (A, X, B, cmd, X))
            # start_new_session puts the shell + all its children in one process
            # group so the watchdog can kill the WHOLE tree (sleep/npm/etc.), not
            # just the shell — otherwise orphaned children keep the pipe open.
            proc = subprocess.Popen(cmd, shell=True, cwd=WORKSPACE,
                                    stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                    text=True, bufsize=1, start_new_session=True)
            killed = {"v": False}
            def _kill():
                killed["v"] = True
                try:
                    os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
                except Exception:
                    try: proc.kill()
                    except Exception: pass
            timer = threading.Timer(BASH_TIMEOUT, _kill); timer.start()
            cap = []
            try:
                for line in proc.stdout:
                    sys.stdout.write("   %s│%s %s" % (D, X, line)); sys.stdout.flush()
                    cap.append(line)
                    if len(cap) > 400:   # keep the tail; errors usually land last
                        cap.pop(0)
            finally:
                proc.wait(); timer.cancel()
            rc = proc.returncode if proc.returncode is not None else -1
            tail = "killed: exceeded %ds" % BASH_TIMEOUT if killed["v"] else "exit %d" % rc
            ok = (rc == 0 and not killed["v"])
            print("   %s│ [%s]%s" % ((G if ok else R), tail, X))
            return "bash " + cmd, trunc(("".join(cap).strip() + "\n[%s]" % tail).strip()), ok, True
        return name, "unknown tool", False, False
    except Exception as e:
        return name, "error: %s" % e, False, False

def verify_tool(obj, result, ok, before=None):
    """Observe the claimed result again after execution.

    The host never supplies this verdict. Read/list/write/edit are checked by a
    second filesystem read; commands are grounded only in their captured exit
    status; environment facts are parsed and compared with the live process.
    """
    if not ok:
        return False, "the tool reported failure"
    name = obj.get("name", "")
    try:
        if name == "env":
            facts = dict(line.split("=", 1) for line in result.splitlines() if "=" in line)
            stable = {
                "cwd": WORKSPACE,
                "machine": platform.machine(),
                "python": platform.python_version(),
                "cpu_count": str(os.cpu_count() or "unknown"),
                "workspace_entries": str(len(os.listdir(WORKSPACE))),
            }
            if any(facts.get(k) != v for k, v in stable.items()):
                return False, "a live environment fact changed on recheck"
            int(facts["workspace_free_bytes"])
            return True, "environment facts re-read"
        if name == "tempdir":
            return (bool(TEMP_ROOTS and os.path.isdir(TEMP_ROOTS[-1])),
                    "managed temporary directory rechecked")
        if name == "read":
            with open(safe_path(obj["path"]), "r", errors="replace") as f:
                actual = trunc(f.read())
            return actual == result, "file content re-read"
        if name == "ls":
            p = safe_path(obj.get("path", "."))
            items = sorted(os.listdir(p))
            actual = "\n".join((i + "/") if os.path.isdir(os.path.join(p, i)) else i for i in items) or "(empty)"
            return actual == result, "directory listing re-read"
        if name == "write":
            with open(safe_path(obj["path"]), "r", errors="replace") as f:
                actual = f.read()
            return actual == str(obj.get("content", "")), "written content re-read"
        if name == "edit":
            old, new = obj.get("old", ""), obj.get("new", "")
            expected = before.replace(old, new, 1) if isinstance(before, str) else None
            with open(safe_path(obj["path"]), "r", errors="replace") as f:
                actual = f.read()
            return expected is not None and actual == expected, "edited content re-read"
        if name == "bash":
            return result.rstrip().endswith("[exit 0]"), "captured process exit status"
    except Exception as exc:
        return False, "verification failed: %s" % exc
    return False, "no independent verifier exists for this tool"

class TerminalToolExecutor:
    """Adapter from a held host proposal to one verified terminal action."""
    def __init__(self, request, yolo):
        self.request = dict(request)
        self.yolo = yolo
        self.label = str(request.get("name", "tool"))
        self.result = "not executed"
        self.ok = False
        self.verified = False
        self.shown = False
        self.requested_executed = False

    def execute(self, action, state):
        requested = str(self.request.get("name", ""))
        selected = str(action.get("type", "idle"))
        safe_analysis = selected == "analyze" and requested in ("env", "ls", "read")
        if selected == "stabilize" and requested != selected:
            self.result = ("not executed: conscience redirected the proposed %s "
                           "action to stabilize; no world change was made" % requested)
            self.ok = True
            return SAIENT_RUNTIME.ActionResult(
                action_type=selected, success=True, simulated=False,
                verified=False, detail={"internal_only": True,
                                        "tool_result": self.result,
                                        "requested_tool": requested,
                                        "requested_tool_executed": False})
        if selected == "analyze" and requested in ("tempdir", "write", "edit", "bash"):
            if requested == "tempdir":
                # Honour the redirect: inspect the controller-owned temp policy
                # without creating anything.  A later tick may allow the
                # original request (including allow-with-uncertainty after the
                # existing bounded clarify loop), but this tick remains a real
                # read-only analysis action.
                root = os.path.realpath(tempfile.gettempdir())
                first = (os.path.isdir(root), os.access(root, os.W_OK | os.X_OK))
                second = (os.path.isdir(root), os.access(root, os.W_OK | os.X_OK))
                self.label = "analyze tempdir policy"
                self.ok = first == second and first[0]
                self.verified = self.ok
                self.result = ("original tempdir not executed; conscience selected analyze\n"
                               "temp_root_available=%s\ntemp_root_accessible=%s" % first)
                return SAIENT_RUNTIME.ActionResult(
                    action_type=selected, success=self.ok, simulated=False,
                    verified=self.verified,
                    detail={"tool_result": self.result, "tool_label": self.label,
                            "verification": "temporary-directory policy rechecked",
                            "requested_tool": requested,
                            "requested_tool_executed": False,
                            "implemented_redirect":
                                "analyze satisfied by a read-only temp policy check"})
            requested_path = str(self.request.get("path", ""))
            if requested_path.startswith("@temp") and TEMP_ROOTS:
                probe = {"name": "ls", "path": "@temp"}
            else:
                parent = os.path.dirname(requested_path) or "."
                probe = {"name": "ls", "path": parent}
            self.label, observed, self.ok, self.shown = run_tool(probe, self.yolo)
            self.verified, verification = verify_tool(probe, observed, self.ok)
            self.result = ("original %s not executed; conscience selected analyze\n%s"
                           % (requested, observed))
            return SAIENT_RUNTIME.ActionResult(
                action_type=selected, success=self.ok, simulated=False,
                verified=self.verified,
                detail={"tool_result": self.result, "tool_label": self.label,
                        "verification": verification,
                        "requested_tool": requested,
                        "requested_tool_executed": False,
                        "implemented_redirect": "analyze satisfied by a read-only listing"})
        if selected != requested and not safe_analysis:
            self.result = ("not executed: conscience redirected the proposed %s "
                           "action to %s" % (requested, selected))
            return SAIENT_RUNTIME.ActionResult(
                action_type=selected, success=False, simulated=False,
                verified=False, detail={"refused": self.result,
                                        "tool_result": self.result,
                                        "requested_tool": requested,
                                        "requested_tool_executed": False})

        before = None
        if requested == "edit":
            try:
                with open(safe_path(self.request["path"]), "r", errors="replace") as f:
                    before = f.read()
            except Exception:
                pass

        self.label, self.result, self.ok, self.shown = run_tool(self.request, self.yolo)
        self.requested_executed = "denied by user" not in self.result
        self.verified, verification = verify_tool(
            self.request, self.result, self.ok, before=before)
        detail = {"tool_result": self.result, "tool_label": self.label,
                  "verification": verification,
                  "requested_tool_executed": self.requested_executed}
        if safe_analysis:
            detail["implemented_redirect"] = "%s satisfied by read-only %s" % (
                selected, requested)
        if not self.verified:
            detail["verification_failures"] = [verification]
        if "denied by user" in self.result:
            detail["refused"] = self.result
        return SAIENT_RUNTIME.ActionResult(
            action_type=selected, success=self.ok, simulated=False,
            verified=self.verified, detail=detail)

def run_bound_tool(obj, yolo):
    executor = TerminalToolExecutor(obj, yolo)
    params = {k: v for k, v in obj.items() if k != "name"}
    reply = SAIENT_BRIDGE.do(str(obj.get("name", "")), executor=executor,
                             params=params)
    return reply, executor

def render_diagnostic_report(journal, controller_events):
    env_rows = [row for row in journal if row["proposed"] == "env"
                and row["executed"] and row["success"] and row["verified"]]
    write_rows = [row for row in journal if row["proposed"] == "write"
                  and row["executed"] and row["success"] and row["verified"]]
    read_rows = [row for row in journal if row["proposed"] == "read"
                 and row["executed"] and row["success"] and row["verified"]]

    observed = []
    if env_rows:
        observed.extend("- " + line for line in env_rows[-1]["result"].splitlines())
    if TEMP_ROOTS:
        observed.append("- managed temporary workspace=" + TEMP_ROOTS[-1])

    decisions = []
    recovery = [row for row in journal
                if row["source"] == "deterministic_recovery_policy"]
    if recovery:
        decisions.append("- The deterministic recovery policy selected "
                         + ", then ".join(row["proposed"] for row in recovery)
                         + " to satisfy the unmet, mechanically checked requirements.")
    else:
        decisions.append("- Host proposals were submitted to Saient's rule policy and conscience.")

    actions = []
    for row in journal:
        actions.append(
            "- tick {tick}: proposed {proposed}; selected {selected}; "
            "conscience={conscience}; executed={executed}; success={success}; "
            "verified={verified}.".format(**row))

    failures = ["- " + event for event in controller_events]
    for row in journal:
        if not row["executed"] or not row["success"]:
            failures.append("- tick {tick}: {result}".format(**row))
    if not failures:
        failures.append("- None observed.")

    evidence = []
    if write_rows:
        artifact_alias = write_rows[-1].get("path") or "@temp/environment_facts.txt"
        try:
            artifact_path = safe_path(artifact_alias)
            with open(artifact_path, "r", errors="replace") as f:
                final_content = f.read()
            read_back = any(row["result"] == trunc(final_content) for row in read_rows)
            evidence.append("- artifact exists=%s" % os.path.isfile(artifact_path))
            evidence.append("- artifact path=" + artifact_path)
            evidence.append("- final independent read matches prior read=%s" % read_back)
            evidence.append("- artifact bytes=%d" % len(final_content.encode()))
        except Exception as exc:
            evidence.append("- final artifact inspection failed: %s" % exc)
    else:
        evidence.append("- No verified artifact write was recorded.")

    unavailable = [row for row in journal
                   if row["executed"] and not row["success"]
                   and "No such file" in row["result"]]
    unavailable_lines = (["- " + row["result"] for row in unavailable]
                         if unavailable else ["- Nothing expected was found unavailable."])

    return ("What I actually observed\n" + "\n".join(observed)
            + "\n\nWhat I decided to do\n" + "\n".join(decisions)
            + "\n\nWhat actions actually occurred\n" + "\n".join(actions)
            + "\n\nFailures and response\n" + "\n".join(failures)
            + "\n\nEvidence of success or failure\n" + "\n".join(evidence)
            + "\n\nExpected but unavailable\n" + "\n".join(unavailable_lines))

def express_final(port, model, user, journal, draft, controller_events):
    """Stage 12 speaks from completed, persisted ticks and verified evidence."""
    diagnostic_report = ("evidence report" in user.lower()
                         and "artifact" in user.lower()
                         and "temporary" in user.lower())
    if diagnostic_report:
        class DiagnosticExpresser:
            def express(self, tick):
                return render_diagnostic_report(journal, controller_events)
        return SAIENT_BRIDGE.say(user, expresser=DiagnosticExpresser())

    evidence = []
    for row in journal[-12:]:
        values = dict(row)
        values["result"] = str(row["result"])[:1400]
        evidence.append(
            "tick={tick} proposed={proposed} selected={selected} conscience={conscience} "
            "redirected={redirected} proposed_tool_executed={executed} "
            "success={success} verified={verified}\n{result}".format(
                **values))
    question = user
    if evidence:
        question += ("\n\nVERIFIED TERMINAL JOURNAL:\n" + "\n\n".join(evidence)
                     + "\n\nHOST DRAFT (use only where the journal supports it):\n"
                     + draft[:3000])
    expresser = ModelExpresser(
        "http://127.0.0.1:%d" % port, model, temperature=0.0,
        max_tokens=700, question=question, deheaded=False,
        top_k=1, repeat_penalty=1.05)
    return SAIENT_BRIDGE.say(user, expresser=expresser)

def show_result(text):
    lines = text.splitlines() or [""]
    for ln in lines[:40]:
        print("   %s│%s %s" % (D, X, ln))
    if len(lines) > 40:
        print("   %s│ …(%d more lines)%s" % (D, len(lines) - 40, X))

def header(port, model, yolo):
    os.system("clear")
    print(A + BANNER + X)
    if port:
        print("   %s●%s %s %s· :%d%s" % (G, X, model, D, port, X))
    else:
        print("   %s●%s no tinyq4 server %s· start a model in Saient%s" % (R, X, D, X))
    mode = (Y + "yolo" + X) if yolo else (D + "confirm" + X)
    if BINDING_ERROR:
        binding = R + "binding failed" + X
    elif BINDING_MANIFEST is not None:
        binding = G + "formally bound" + X
    else:
        binding = Y + "binding pending" + X
    print("   %sagent%s · env tempdir read ls write edit bash · %s · %s · %s/yolo /tools /clear /exit%s" % (D, X, binding, mode, D, X))
    print("   %scwd %s%s\n" % (D, WORKSPACE, X))
    if BINDING_ERROR:
        print("   %sSaient runtime unavailable: %s%s\n" % (R, BINDING_ERROR, X))

def read_user_prompt():
    """Read one typed line or coalesce a pasted multiline prompt.

    `input()` stops at the first newline, so a pasted task used to become many
    unrelated turns queued behind one another. After the first line, collect
    any additional lines already waiting in the cross-platform reader queue.
    A person typing normally pays only the short debounce below.
    """
    first = read_line("   %s❯%s " % (A, X))
    lines = [first]
    while True:
        try:
            extra = INPUT_QUEUE.get(timeout=0.25)
        except queue.Empty:
            break
        if extra is None:
            break
        lines.append(extra)
    return "\n".join(lines).strip()

TOOL_KEYS = {
    "env": {"name"},
    "tempdir": {"name", "prefix"},
    "read": {"name", "path"},
    "ls": {"name", "path"},
    "write": {"name", "path", "content"},
    "edit": {"name", "path", "old", "new"},
    "bash": {"name", "command"},
}

def tool_argument_error(tool):
    name = str(tool.get("name", ""))
    if name not in TOOL_KEYS:
        return "unknown tool %r" % name
    extra = set(tool) - TOOL_KEYS[name]
    if extra:
        return "%s does not accept %s" % (name, ", ".join(sorted(extra)))
    for value in tool.values():
        if isinstance(value, str) and "&amp;" in value:
            return "HTML-escaped '&amp;' is not an exact tool argument; use '&'"
    if "path" in tool:
        path = str(tool.get("path", ""))
        if os.path.isabs(path):
            return "use a workspace-relative path or @temp, not an absolute path"
        if re.search(r"[/._@-]\s|\s[/._@]", path):
            return "path contains whitespace beside punctuation; preserve the exact path"
    return None

def looks_unfinished(text):
    lower = text.lower()
    return ("```bash" in lower or "`bash` command" in lower
            or ("```" in text and any(word in lower for word in
                                       ("write", "read", " ls ", " cat ", "echo "))))

def completion_error(user, journal):
    """Enforce explicit, mechanically checkable completion requirements.

    This is deliberately narrow: it does not guess whether an arbitrary coding
    task is finished. It only holds a host to operations the user named plainly
    enough for the controller to verify from its own journal.
    """
    lower = user.lower()
    completed = [row for row in journal
                 if row["executed"] and row["success"] and row["verified"]]
    names = [row["proposed"] for row in completed]
    missing = []
    needs_temp = "temporary" in lower and any(
        word in lower for word in ("workspace", "directory", "folder"))
    needs_artifact = "artifact" in lower and any(
        word in lower for word in ("create", "produce", "make", "write"))
    needs_facts = ("three real facts" in lower
                   or ("three" in lower and "facts" in lower))
    needs_recheck = needs_artifact and any(
        word in lower for word in ("verify", "inspect the result", "read back"))
    if needs_temp and "tempdir" not in names:
        missing.append("the requested managed temporary workspace was not created")
    mutations = [i for i, row in enumerate(journal)
                 if row["executed"] and row["success"] and row["verified"]
                 and row["proposed"] in ("write", "edit")]
    if needs_artifact and not mutations:
        missing.append("no verified artifact-creating action occurred")
    if needs_facts:
        if "env" not in names:
            missing.append("the environment was not inspected with a verified observation")
        elif mutations and artifact_environment_fact_count(journal) < 3:
            missing.append("the artifact does not contain three verified environment facts")
    if needs_recheck and mutations:
        last_mutation = mutations[-1]
        if not any(i > last_mutation and row["executed"]
                   and row["success"] and row["verified"]
                   and row["proposed"] in ("read", "ls")
                   for i, row in enumerate(journal)):
            missing.append("the artifact was not independently read or listed after creation")
    return "; ".join(missing) if missing else None

def artifact_environment_fact_count(journal, write_row=None):
    """Count exact environment observations preserved in the written artifact."""
    env_rows = [row for row in journal if row["proposed"] == "env"
                and row["executed"] and row["success"] and row["verified"]]
    if not env_rows:
        return 0
    if write_row is None:
        writes = [row for row in journal if row["proposed"] == "write"
                  and row["executed"] and row["success"] and row["verified"]]
        if not writes:
            return 0
        write_row = writes[-1]
    try:
        with open(safe_path(write_row.get("path") or ""), "r", errors="replace") as f:
            content = f.read()
    except Exception:
        return 0
    facts = [line for line in env_rows[-1]["result"].splitlines() if "=" in line]
    return sum(1 for fact in facts if fact in content)

def diagnostic_recovery_tool(user, journal):
    """A bounded non-model route for the explicit diagnostic-artifact task."""
    lower = user.lower()
    if "artifact" not in lower or "temporary" not in lower:
        return None
    successful = [row for row in journal
                  if row["executed"] and row["success"] and row["verified"]]
    names = [row["proposed"] for row in successful]
    if "env" not in names:
        return {"name": "env"}
    if "tempdir" not in names:
        return {"name": "tempdir", "prefix": "diagnostic"}

    writes = [(i, row) for i, row in enumerate(journal)
              if row["proposed"] == "write"]
    successful_writes = [(i, row) for i, row in writes
                         if row["executed"] and row["success"] and row["verified"]
                         and artifact_environment_fact_count(journal, row) >= 3]
    if not successful_writes:
        if writes and not (writes[-1][1]["executed"]
                           and writes[-1][1]["success"]
                           and writes[-1][1]["verified"]):
            last_write = writes[-1][0]
            write_row = writes[-1][1]
            redirect_already_probed = (
                write_row.get("selected") == "analyze"
                and write_row.get("success") and write_row.get("verified")
                and bool(write_row.get("implemented_redirect")))
            # TerminalToolExecutor already implements a conscience `analyze`
            # redirect for write/edit as a separately verified, read-only
            # parent listing.  Treat that as the requested probe.  Inserting a
            # second `ls` here reset the bounded clarify loop on every pass, so
            # the same write/list pair consumed the entire turn before the
            # final independent artifact read could happen.
            if not redirect_already_probed and not any(
                    i > last_write and row["executed"]
                    and row["proposed"] == "ls"
                    and row["success"] and row["verified"]
                    for i, row in enumerate(journal)):
                return {"name": "ls", "path": "@temp"}
        env_result = next(row["result"] for row in successful
                          if row["proposed"] == "env")
        return {
            "name": "write",
            "path": "@temp/environment_facts.txt",
            "content": "Saient diagnostic environment evidence\n\n" + env_result + "\n",
        }

    write_index, write_row = successful_writes[-1]
    if not any(i > write_index and row["executed"]
               and row["proposed"] in ("read", "ls")
               and row["success"] and row["verified"]
               for i, row in enumerate(journal)):
        return {"name": "read", "path":
                write_row.get("path") or "@temp/environment_facts.txt"}
    return None

def main():
    port, model = find_server()
    yolo = False
    sys_msg = {"role": "system", "content": SYSTEM.replace("__WS__", WORKSPACE).replace("__OS__", platform.system() or "this OS")}
    header(port, model, yolo)
    while True:
        try:
            user = read_user_prompt()
        except (EOFError, KeyboardInterrupt):
            print(); break
        if not user:
            continue
        if user in ("/exit", "/quit", "/q"):
            break
        if user in ("/clear", "/reset"):
            header(port, model, yolo); continue
        if user == "/yolo":
            yolo = not yolo
            msg = "ON — tools run without asking" if yolo else "OFF — confirm writes & bash"
            print("   %syolo %s%s\n" % (Y, msg, X)); continue
        if user == "/tools":
            print("   %senv · tempdir · read · ls · write · edit · bash%s\n" % (D, X)); continue
        if user == "/help":
            print("   %s/yolo · /tools · /clear · /exit%s\n" % (D, X)); continue
        if not port:
            port, model = find_server()
            if not port:
                print("   %sno server — load a model in Saient first%s\n" % (R, X)); continue
            header(port, model, yolo)
        if BINDING_ERROR:
            print("   %sSaient runtime binding failed; no host fallback was used: %s%s\n" %
                  (R, BINDING_ERROR, X))
            continue
        if not ensure_formal_binding(port):
            print("   %sSaient host did not pass formal binding; no host fallback was used: %s%s\n" %
                  (R, BINDING_ERROR, X))
            continue
        if BINDING_MANIFEST is not None:
            print("   %sformal binding %s · %s%s\n" %
                  (G, BINDING_MANIFEST["minimum_interface"], model, X))
        messages = [sys_msg, {"role": "user", "content": user}]
        journal = []
        controller_events = []
        invalid_responses = 0
        premature_finals = 0
        recovery_active = False
        # ── Tool loop ──────────────────────────────────────────────────────
        tool_counts = {}
        for _ in range(MAX_STEPS):
            forced = diagnostic_recovery_tool(user, journal) if recovery_active else None
            if forced is not None:
                print("\n   %srecovery policy selected %s%s" %
                      (Y, forced["name"], X))
                text = "```json\n%s\n```" % json.dumps(forced, separators=(",", ":"))
            else:
                print("\n   %sproposal%s  " % (D, X), end="", flush=True)
                try:
                    text = stream(port, messages)
                except KeyboardInterrupt:
                    print("%sinterrupted%s" % (Y, X)); break
                except Exception:
                    np, nm = find_server()
                    if np:
                        port, model = np, nm
                        try:
                            text = stream(port, messages)
                        except Exception as e:
                            print("%serror: %s%s" % (R, e, X)); break
                    else:
                        print("%sconnection lost — is a model loaded?%s" % (R, X)); port = None; break
            tool = extract_tool(text)
            proposal_source = ("deterministic_recovery_policy"
                               if forced is not None else "host")
            if not tool:
                if looks_unfinished(text) and invalid_responses < 3:
                    invalid_responses += 1
                    result = ("not executed: prose and shell fences are not tool calls; "
                              "return one fenced JSON tool block, or a final factual report "
                              "only after verification")
                    print("%srejected incomplete host output%s" % (R, X))
                    controller_events.append(
                        "Host emitted unexecuted prose or shell fences; the controller rejected it and requested one tool proposal.")
                    if diagnostic_recovery_tool(user, journal) is not None:
                        recovery_active = True
                    messages.append({"role": "assistant", "content": text[-2000:]})
                    messages.append({"role": "user", "content":
                                     "[controller feedback]\n" + result})
                    continue
                incomplete = completion_error(user, journal)
                if incomplete:
                    premature_finals += 1
                    print("%srejected premature completion%s" % (R, X))
                    controller_events.append(
                        "Host stopped before the explicit completion requirements; the controller rejected completion and continued through the recovery policy.")
                    recovery = diagnostic_recovery_tool(user, journal)
                    if recovery is not None:
                        tool = recovery
                        proposal_source = "deterministic_recovery_policy"
                        recovery_active = True
                        print("   %srecovery policy selected %s%s" %
                              (Y, tool["name"], X))
                    else:
                        if premature_finals >= 4:
                            show_result("stopped incomplete: " + incomplete)
                            break
                        messages.append({"role": "assistant", "content": text[-2000:]})
                        messages.append({"role": "user", "content":
                                         "[controller feedback]\nnot complete: " + incomplete
                                         + ". Continue with one fenced JSON tool call."})
                        continue
                if tool:
                    pass
                else:
                    try:
                        final_reply = express_final(
                            port, model, user, journal, text, controller_events)
                    except Exception as exc:
                        print("%sexpression failed: %s%s" % (R, exc, X))
                        break
                    print("\r   %ssaient%s  %s" % (A, X, final_reply.text))
                    break
            invalid_responses = 0
            premature_finals = 0
            problem = tool_argument_error(tool)
            if problem:
                print("%srejected invalid tool proposal%s" % (R, X))
                controller_events.append("Invalid tool proposal rejected: " + problem)
                if diagnostic_recovery_tool(user, journal) is not None:
                    recovery_active = True
                messages.append({"role": "assistant", "content":
                                 "```json\n%s\n```" % json.dumps(tool, separators=(",", ":"))})
                messages.append({"role": "user", "content":
                                 "[controller feedback]\nnot executed: " + problem})
                continue
            # Keep only the one proposal that can actually run. Host prose and
            # extra unexecuted tool blocks never become the next turn's facts.
            messages.append({"role": "assistant", "content":
                             "```json\n%s\n```" % json.dumps(tool, separators=(",", ":"))})
            tool_key = json.dumps(tool, sort_keys=True, separators=(",", ":"))
            tool_counts[tool_key] = tool_counts.get(tool_key, 0) + 1
            repeat_count = tool_counts[tool_key]
            if proposal_source == "host" and repeat_count == 3:
                result = "not executed: this identical tool call has already run twice in this turn; use the existing results and choose a different next step"
                print("\n   %s⚙%s %srepeat blocked%s" % (R, X, B, X))
                show_result(result)
                messages.append({"role": "user", "content": "[controller feedback]\n" + result})
                continue
            if proposal_source == "host" and repeat_count >= 4:
                print("\n   %sstopped: the model requested the same tool call four times in one turn%s" % (R, X))
                break
            try:
                reply, executor = run_bound_tool(tool, yolo)
            except Exception as exc:
                result = "Saient bridge error: %s: %s" % (type(exc).__name__, exc)
                print("%sbridge error%s" % (R, X))
                show_result(result)
                messages.append({"role": "user", "content":
                                 "[controller feedback]\n" + result})
                continue
            result = str(reply.detail.get("tool_result", executor.result))
            if not executor.shown:
                colour = G if reply.success and reply.verified else R
                print("\r   %s⚙%s %s%s%s" % (colour, X, B, executor.label, X))
                show_result(result)
            row = {
                "tick": reply.tick,
                "proposed": str(tool.get("name", "")),
                "selected": str(reply.action),
                "conscience": str(reply.conscience),
                "redirected": bool(reply.redirected),
                "success": bool(reply.success),
                "verified": bool(reply.verified),
                "executed": bool(reply.detail.get(
                    "requested_tool_executed", executor.requested_executed)),
                "implemented_redirect": str(reply.detail.get(
                    "implemented_redirect", "")),
                "result": result,
                "path": str(tool.get("path", "")),
                "source": proposal_source,
            }
            journal.append(row)
            if ("artifact" in user.lower() and "temporary" in user.lower()
                    and (proposal_source == "deterministic_recovery_policy"
                         or not row["executed"] or not row["success"])):
                recovery_active = completion_error(user, journal) is not None
            messages.append({"role": "user", "content":
                             "[Saient tick {tick} · source={source} · conscience={conscience} · selected={selected} · redirected={redirected} · proposed_tool_executed={executed} · success={success} · verified={verified}]\n[tool result · {proposed}]\n{result}".format(**row)})
        else:
            print("\n   %sreached step limit (%d) — type to continue%s" % (Y, MAX_STEPS, X))
        print("\n")

def workspace_contract_check():
    """Exercise production path resolution without a model or a mock filesystem."""
    cwd = os.path.realpath(os.getcwd())
    expected = os.path.realpath(os.environ[WORKSPACE_ENV])
    if WORKSPACE != expected or cwd != expected:
        raise AssertionError("cwd, SAIENT_WORKSPACE and tool root are not identical")

    parent = ".saient/path contract begining with spaces"
    rel = parent + "/round trip.txt"
    resolved = safe_path(rel)
    operations = []

    label, result, ok, shown = run_tool(
        {"name": "write", "path": rel, "content": "alpha"}, True)
    verified, _ = verify_tool(
        {"name": "write", "path": rel, "content": "alpha"}, result, ok)
    operations.append({"name": label, "ok": ok, "verified": verified})

    label, result, ok, shown = run_tool({"name": "ls", "path": parent}, True)
    verified, _ = verify_tool({"name": "ls", "path": parent}, result, ok)
    operations.append({"name": label, "ok": ok, "verified": verified})
    if "round trip.txt" not in result:
        raise AssertionError("the written file was absent from the next listing")

    label, result, ok, shown = run_tool({"name": "read", "path": rel}, True)
    verified, _ = verify_tool({"name": "read", "path": rel}, result, ok)
    operations.append({"name": label, "ok": ok, "verified": verified})
    if result != "alpha":
        raise AssertionError("the next read did not use the same canonical root")

    edit = {"name": "edit", "path": rel, "old": "alpha", "new": "beta"}
    label, result, ok, shown = run_tool(edit, True)
    verified, _ = verify_tool(edit, result, ok, before="alpha")
    operations.append({"name": label, "ok": ok, "verified": verified})
    if not all(row["ok"] and row["verified"] for row in operations):
        raise AssertionError("one or more canonical workspace operations failed")
    if safe_path(rel) != resolved:
        raise AssertionError("a later action resolved the same path differently")

    print(json.dumps({
        "result": "PASS",
        "workspace": WORKSPACE,
        "resolved_path": resolved,
        "operations": operations,
    }, separators=(",", ":")))
    return 0

if __name__ == "__main__":
    if "--workspace-contract-check" in sys.argv:
        raise SystemExit(workspace_contract_check())
    main()
"####;

/// Write the Saient bash init file (and the agent TUI it launches) and return the
/// rcfile path. Returns None if $HOME is unset or the files can't be written
/// (the caller then falls back to a plain shell).
/// Write the agent CLI (cross-platform) into the config dir and return that dir.
fn write_saient_cli() -> Option<std::path::PathBuf> {
    let dir = crate::setup::config_dir();
    std::fs::create_dir_all(&dir).ok()?;
    std::fs::write(dir.join("saient_cli.py"), SAIENT_CLI_PY).ok()?;
    Some(dir)
}

/// Unix: write the bash rcfile that defines the `saient` command. Returns its path.
#[cfg(unix)]
fn write_saient_rcfile() -> Option<std::path::PathBuf> {
    let dir = write_saient_cli()?;
    let path = dir.join("saient.bashrc");
    std::fs::write(&path, SAIENT_BASHRC).ok()?;
    Some(path)
}

/// Windows: write a `saient.cmd` shim that runs the CLI with the resolved Python.
/// Returns the dir to prepend to PATH so typing `saient` works in the terminal.
#[cfg(windows)]
fn write_saient_cmd() -> Option<std::path::PathBuf> {
    let dir = write_saient_cli()?;
    let py = crate::resolve::find_python()
        .map(|p| p.to_string_lossy().into_owned())
        .unwrap_or_else(|_| "python".into());
    let cmd = format!("@echo off\r\n\"{py}\" \"%~dp0saient_cli.py\" %*\r\n");
    std::fs::write(dir.join("saient.cmd"), cmd).ok()?;
    Some(dir)
}

// ── Tauri commands ────────────────────────────────────────────────────────────

#[tauri::command]
pub async fn pty_spawn(
    window: tauri::WebviewWindow,
    handle: tauri::State<'_, PtyHandle>,
    cwd: String,
    cols: u16,
    rows: u16,
    server_port: Option<u16>,
) -> Result<(), String> {
    let workspace = canonical_workspace(&cwd)?;

    // Kill any existing session before spawning a new one.
    if let Some(old) = handle.lock().map_err(|e| e.to_string())?.take() {
        kill_session(old);
    }

    let pty_system = native_pty_system();
    let pair = pty_system
        .openpty(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
        .map_err(|e| e.to_string())?;

    // Build the shell command per-platform.
    #[cfg(unix)]
    let mut cmd = {
        // bash with our Saient rcfile so the `saient` command + banner are present;
        // fall back to a plain $SHELL if bash or the rcfile is unavailable.
        let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/bash".into());
        let rcfile = write_saient_rcfile();
        let bash = if shell.ends_with("bash") {
            Some(shell.clone())
        } else if std::path::Path::new("/bin/bash").exists() {
            Some("/bin/bash".to_string())
        } else {
            None
        };
        match (&bash, &rcfile) {
            (Some(bash_path), Some(rc)) => {
                let mut c = CommandBuilder::new(bash_path);
                c.arg("--rcfile");
                c.arg(rc);
                c.arg("-i");
                c
            }
            _ => CommandBuilder::new(&shell),
        }
    };

    #[cfg(windows)]
    let mut cmd = {
        // PowerShell terminal; put a saient.cmd shim on PATH so `saient` works, and
        // print the same greeting the bash terminal shows (PowerShell has no rcfile).
        let mut c = CommandBuilder::new("powershell.exe");
        c.arg("-NoLogo");
        c.arg("-NoExit");
        c.arg("-Command");
        c.arg("Write-Host ''; Write-Host 'saient' -ForegroundColor Cyan -NoNewline; Write-Host ' > type ' -NoNewline; Write-Host 'saient' -ForegroundColor White -NoNewline; Write-Host ' to launch the agent'; Write-Host ''");
        if let Some(dir) = write_saient_cmd() {
            let existing = std::env::var("PATH").unwrap_or_default();
            c.env("PATH", format!("{};{}", dir.to_string_lossy(), existing));
        }
        c
    };

    cmd.cwd(&workspace);
    cmd.env("SAIENT_WORKSPACE", workspace.as_os_str());
    cmd.env("TERM", "xterm-256color");
    cmd.env("COLORTERM", "truecolor");
    cmd.env(crate::paths::DATA_DIR_ENV, crate::paths::data_dir().to_string_lossy().into_owned());
    cmd.env(crate::paths::CONFIG_DIR_ENV, crate::paths::config_dir().to_string_lossy().into_owned());
    cmd.env(crate::paths::SHARE_DIR_ENV, crate::paths::share_dir().to_string_lossy().into_owned());
    cmd.env(crate::paths::MODELS_DIR_ENV, crate::paths::models_dir().to_string_lossy().into_owned());
    if let Some(runtime) = crate::saient_loop::runtime_dir() {
        cmd.env(crate::saient_loop::RUNTIME_DIR_ENV,
                runtime.to_string_lossy().into_owned());
    }
    cmd.env(crate::saient_loop::STATE_DIR_ENV,
            crate::saient_loop::state_dir().to_string_lossy().into_owned());
    cmd.env("PYTHONDONTWRITEBYTECODE", "1");
    // The terminal agent is allowed to reach only the selected numeric
    // loopback model endpoint. Never inherit a proxy that could redirect it.
    cmd.env("NO_PROXY", "127.0.0.1,::1");
    cmd.env("no_proxy", "127.0.0.1,::1");
    for key in ["HTTP_PROXY", "HTTPS_PROXY", "ALL_PROXY", "http_proxy", "https_proxy", "all_proxy"] {
        cmd.env(key, "");
    }
    // Tell the agent CLI exactly which port the model server is on, so it doesn't
    // have to scan /proc (which is Linux-only and misses dynamic ports anyway).
    if let Some(port) = server_port {
        cmd.env("SAIENT_SERVER_PORT", port.to_string());
    }

    let child = pair.slave.spawn_command(cmd).map_err(|e| e.to_string())?;
    drop(pair.slave); // close slave fd in parent — child inherited its own copy

    let mut reader = pair.master.try_clone_reader().map_err(|e| e.to_string())?;
    let     writer = pair.master.take_writer()      .map_err(|e| e.to_string())?;

    let stop      = Arc::new(AtomicBool::new(false));
    let stop_read = stop.clone();

    // Reader thread: forwards PTY output to the frontend as "pty-data" events.
    std::thread::spawn(move || {
        let mut buf = [0u8; 4096];
        loop {
            if stop_read.load(Ordering::Relaxed) { break; }
            match reader.read(&mut buf) {
                Ok(0) | Err(_) => break,
                Ok(n) => {
                    // from_utf8_lossy is fine for terminal output (ANSI + text).
                    let data = String::from_utf8_lossy(&buf[..n]).into_owned();
                    let _ = window.emit("pty-data", data);
                }
            }
        }
    });

    *handle.lock().map_err(|e| e.to_string())? = Some(PtySession {
        writer,
        master: pair.master,
        child,
        stop,
    });

    Ok(())
}

/// Write keystrokes from xterm.js into the PTY master.
#[tauri::command]
pub fn pty_write(handle: tauri::State<'_, PtyHandle>, data: String) -> Result<(), String> {
    let mut g = handle.lock().map_err(|e| e.to_string())?;
    if let Some(s) = g.as_mut() {
        s.writer.write_all(data.as_bytes()).map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Notify the kernel of a terminal resize so line-wrapping and full-screen apps stay correct.
#[tauri::command]
pub fn pty_resize(handle: tauri::State<'_, PtyHandle>, cols: u16, rows: u16) -> Result<(), String> {
    let g = handle.lock().map_err(|e| e.to_string())?;
    if let Some(s) = g.as_ref() {
        s.master
            .resize(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
            .map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Kill the shell process and clean up the PTY session.
#[tauri::command]
pub fn pty_kill(handle: tauri::State<'_, PtyHandle>) -> Result<(), String> {
    if let Some(old) = handle.lock().map_err(|e| e.to_string())?.take() {
        kill_session(old);
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::{canonical_workspace, SAIENT_CLI_PY};

    #[test]
    fn generated_cli_keeps_multiline_pastes_in_one_turn() {
        assert!(SAIENT_CLI_PY.contains("def read_user_prompt():"));
        assert!(SAIENT_CLI_PY.contains("INPUT_QUEUE.get(timeout=0.25)"));
        assert!(SAIENT_CLI_PY.contains("threading.Thread(target=_stdin_reader, daemon=True).start()"));
        assert!(SAIENT_CLI_PY.contains("user = read_user_prompt()"));
    }

    #[test]
    fn generated_cli_supports_isolated_diagnostics() {
        assert!(SAIENT_CLI_PY.contains("if name == \"env\":"));
        assert!(SAIENT_CLI_PY.contains("if name == \"tempdir\":"));
        assert!(SAIENT_CLI_PY.contains("TEMP_ROOTS.append(root)"));
        assert!(SAIENT_CLI_PY.contains("if p == \"@temp\" or p.startswith(\"@temp/\")"));
        assert!(SAIENT_CLI_PY.contains(
            "if proposal_source == \"host\" and repeat_count == 3:"));
        assert!(SAIENT_CLI_PY.contains(
            "analyze satisfied by a read-only temp policy check"));
        assert!(SAIENT_CLI_PY.contains("redirect_already_probed"));
    }

    #[test]
    fn generated_cli_enters_saient_instead_of_impersonating_her() {
        assert!(SAIENT_CLI_PY.contains("SAIENT_BRIDGE.do"));
        assert!(SAIENT_CLI_PY.contains("SAIENT_BRIDGE.say"));
        assert!(SAIENT_CLI_PY.contains("ensure_formal_binding(port)"));
        assert!(SAIENT_CLI_PY.contains("formally bound"));
        assert!(SAIENT_CLI_PY.contains("no host fallback was used"));
        assert!(!SAIENT_CLI_PY.contains("You are Saient, a local coding agent"));
    }

    #[test]
    fn generated_cli_keeps_random_temp_paths_out_of_host_context() {
        assert!(SAIENT_CLI_PY.contains("return \"tempdir\", \"handle=@temp\", True, True"));
        assert!(SAIENT_CLI_PY.contains("never the random absolute path"));
    }

    #[test]
    fn canonical_workspace_survives_unusual_spelling_spaces_and_later_actions() {
        let temporary = tempfile::tempdir().unwrap();
        let workspace = temporary.path().join("Saient begining  odd spelling");
        std::fs::create_dir_all(&workspace).unwrap();
        let canonical = canonical_workspace(workspace.to_str().unwrap()).unwrap();
        assert_eq!(canonical, std::fs::canonicalize(&workspace).unwrap());

        let script = temporary.path().join("saient_cli.py");
        std::fs::write(&script, SAIENT_CLI_PY).unwrap();
        let python = crate::resolve::find_python().unwrap();
        let output = std::process::Command::new(python)
            .arg(&script)
            .arg("--workspace-contract-check")
            .current_dir(&workspace)
            .env("SAIENT_WORKSPACE", &canonical)
            .env("PYTHONDONTWRITEBYTECODE", "1")
            .output()
            .unwrap();
        assert!(output.status.success(), "{}", String::from_utf8_lossy(&output.stderr));
        let payload: serde_json::Value = serde_json::from_slice(&output.stdout).unwrap();
        assert_eq!(payload["result"], "PASS");
        assert_eq!(payload["workspace"], canonical.to_string_lossy().as_ref());
        assert_eq!(payload["operations"].as_array().unwrap().len(), 4);
        assert!(payload["operations"].as_array().unwrap().iter().all(|row| {
            row["ok"] == true && row["verified"] == true
        }));
        assert_eq!(
            std::fs::read_to_string(
                workspace.join(".saient/path contract begining with spaces/round trip.txt")
            ).unwrap(),
            "beta"
        );
    }
}
