// Real PTY terminal — spawns $SHELL in a pseudo-terminal, streams I/O via Tauri events.
// Frontend uses xterm.js; backend uses portable-pty for cross-platform PTY creation.

use portable_pty::{native_pty_system, CommandBuilder, PtySize};
use std::io::{Read, Write};
use std::sync::{
    atomic::{AtomicBool, Ordering},
    Arc, Mutex,
};
use tauri::Emitter;

pub struct PtySession {
    writer: Box<dyn Write + Send>,
    master: Box<dyn portable_pty::MasterPty + Send>,
    child:  Box<dyn portable_pty::Child  + Send + Sync>,
    stop:   Arc<AtomicBool>,
}

pub type PtyHandle = Arc<Mutex<Option<PtySession>>>;

pub fn new_handle() -> PtyHandle {
    Arc::new(Mutex::new(None))
}

fn kill_session(mut session: PtySession) {
    session.stop.store(true, Ordering::Relaxed);
    let _ = session.child.kill();
    // Drop order: writer, master, child, stop — killing child closes the slave PTY,
    // which causes the reader thread's read() to return EIO and exit.
}

// ── Saient terminal init ───────────────────────────────────────────────────────
// Two generated files written to ~/.config/ai-workshop/ on each PTY spawn:
//   saient.bashrc  — sourced via `bash --rcfile`; defines the `saient` command and
//                   prints a greeting. Re-sources ~/.bashrc so the user's env works.
//   saient_cli.py  — the Saient agent TUI. Pure-stdlib Python: renders the ASCII
//                   splash, finds the running tinyq4 server, streams chat over its
//                   OpenAI-compatible SSE endpoint. No external deps, no opencode.

const SAIENT_BASHRC: &str = r##"# Saient terminal init — generated by Saient. Safe to edit; regenerated on app launch.
unset npm_config_prefix 2>/dev/null
[ -f "$HOME/.bashrc" ] && source "$HOME/.bashrc"

# Launch the Saient agent TUI (talks to the local tinyq4 server).
saient() {
  python3 "$HOME/.config/ai-workshop/saient_cli.py" "$@"
}

# Greeting shown when the terminal opens.
printf '\n\033[38;2;108;142;245msaient\033[0m \033[2m›\033[0m type \033[1msaient\033[0m \033[2mto launch the agent\033[0m\n\n'

# To boot straight into the agent every time the terminal opens, uncomment:
# saient
"##;

const SAIENT_CLI_PY: &str = r####"#!/usr/bin/env python3
# Saient — local coding agent TUI. Generated by Saient.
# Talks to the tinyq4 OpenAI-compatible server the app already manages, and can
# act on the workspace via a ReAct-style tool loop (read/ls/write/edit/bash).
# Pure standard library: no pip installs required.
import sys, os, json, re, signal, subprocess, threading, urllib.request

A = "\033[38;2;108;142;245m"   # accent blue
D = "\033[2m"                  # dim
B = "\033[1m"                  # bold
G = "\033[38;2;0;214;143m"     # green
R = "\033[38;2;248;113;113m"   # red
Y = "\033[38;2;245;166;35m"    # amber
X = "\033[0m"                  # reset

BANNER = r"""
   ██╗  ██╗ █████╗ ██╗██████╗  ██████╗
   ██║ ██╔╝██╔══██╗██║██╔══██╗██╔═══██╗
   █████╔╝ ███████║██║██████╔╝██║   ██║
   ██╔═██╗ ██╔══██║██║██╔══██╗██║   ██║
   ██║  ██╗██║  ██║██║██║  ██║╚██████╔╝
   ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝╚═╝  ╚═╝ ╚═════╝
"""

PORTS = [18081, 18082, 33115, 18080]
WORKSPACE = os.path.realpath(os.getcwd())
MAX_STEPS = 25          # tool-loop iterations per user turn
MAX_OUT   = 4000        # max chars of a tool result fed back to the model

SYSTEM = """You are Saient, a local coding agent. You work inside this directory:
__WS__

You can ACT using tools. To use a tool, reply with ONE fenced json block and nothing else:
```json
{"name": "read", "path": "src/main.py"}
```

Tools:
- read  {"name":"read","path":"<file>"}                          read a file
- ls    {"name":"ls","path":"<dir>"}                             list a directory ("." = current)
- write {"name":"write","path":"<file>","content":"<text>"}      create or overwrite a file
- edit  {"name":"edit","path":"<file>","old":"<exact>","new":"<replacement>"}  replace text once
- bash  {"name":"bash","command":"<shell command>"}              run a command in the workspace

Workflow:
- Briefly state your plan, then emit a SINGLE tool block to gather info or make a change.
- You will receive the tool result, then continue with the next step.
- Use 'edit' for existing files (include enough surrounding text so 'old' is unique). Use 'write' for new files.
- All paths are relative to the workspace; never try to escape it.
- When the task is fully complete, reply with a short normal message and NO json block.
"""

def discover_ports():
    # The app spawns tinyq4 on a dynamically-allocated free port, so static probe
    # ports aren't enough. Scan /proc for any `tinyq4 ... --server <port>` process
    # (matches how the Rust side discovers servers), then fall back to known ports.
    found = []
    try:
        for pid in os.listdir("/proc"):
            if not pid.isdigit():
                continue
            try:
                with open("/proc/%s/cmdline" % pid, "rb") as f:
                    args = [a.decode("utf-8", "replace") for a in f.read().split(b"\x00") if a]
            except Exception:
                continue
            if not args or not any("tinyq4" in a for a in args):
                continue
            for i, a in enumerate(args):
                if a == "--server" and i + 1 < len(args):
                    try:
                        found.append(int(args[i + 1]))
                    except ValueError:
                        pass
    except Exception:
        pass
    seen, ordered = set(), []
    for p in found + PORTS:
        if p not in seen:
            seen.add(p); ordered.append(p)
    return ordered

def find_server():
    for p in discover_ports():
        try:
            r = urllib.request.urlopen("http://127.0.0.1:%d/health" % p, timeout=0.4)
            if r.status == 200:
                model = "local model"
                try:
                    m = json.load(urllib.request.urlopen("http://127.0.0.1:%d/v1/models" % p, timeout=0.4))
                    model = m["data"][0]["id"]
                except Exception:
                    pass
                return p, model
        except Exception:
            continue
    return None, None

def stream(port, messages):
    body = json.dumps({"messages": messages, "stream": True,
                       "max_tokens": 2048, "temperature": 0.3}).encode()
    req = urllib.request.Request(
        "http://127.0.0.1:%d/v1/chat/completions" % port,
        data=body, headers={"Content-Type": "application/json"})
    out = ""
    in_think = False
    with urllib.request.urlopen(req) as resp:
        for raw in resp:
            line = raw.decode("utf-8", "replace").strip()
            if not line.startswith("data:"):
                continue
            payload = line[5:].strip()
            if payload == "[DONE]":
                break
            try:
                delta = json.loads(payload)["choices"][0]["delta"]
            except Exception:
                continue
            think = delta.get("reasoning_content")
            content = delta.get("content")
            if think:
                if not in_think:
                    sys.stdout.write(D); in_think = True
                sys.stdout.write(think); sys.stdout.flush()
            if content:
                if in_think:
                    sys.stdout.write(X); in_think = False
                sys.stdout.write(content); sys.stdout.flush()
                out += content
    if in_think:
        sys.stdout.write(X)
    return out

# ── Tools ──────────────────────────────────────────────────────────────────
def safe_path(p):
    full = os.path.realpath(os.path.join(WORKSPACE, p))
    if full != WORKSPACE and not full.startswith(WORKSPACE + os.sep):
        raise ValueError("path escapes workspace: %s" % p)
    return full

def trunc(s):
    return s if len(s) <= MAX_OUT else s[:MAX_OUT] + ("\n…[truncated %d chars]" % (len(s) - MAX_OUT))

FENCE = re.compile(r"```(?:json)?\s*(\{.*?\})\s*```", re.S)

def extract_tool(text):
    cand = None
    m = FENCE.search(text)
    if m:
        cand = m.group(1)
    else:
        i = text.find('{"name"')
        if i == -1:
            i = text.find('{ "name"')
        if i != -1:
            depth = 0
            for j in range(i, len(text)):
                if text[j] == "{": depth += 1
                elif text[j] == "}":
                    depth -= 1
                    if depth == 0:
                        cand = text[i:j+1]; break
    if not cand:
        return None
    try:
        obj = json.loads(cand)
    except Exception:
        return None
    return obj if isinstance(obj, dict) and "name" in obj else None

def confirm(summary, yolo):
    if yolo:
        return True
    try:
        ans = input("   %sallow%s %s %s[y/N]%s " % (Y, X, summary, D, X)).strip().lower()
    except (EOFError, KeyboardInterrupt):
        print(); return False
    return ans in ("y", "yes")

BASH_TIMEOUT = 600   # seconds — long enough for npm/expo/pip installs

# Tools return (label, result_for_model, ok, shown). When shown is True the tool
# already printed its own ⚙ header + output (used by bash, which streams live).
def run_tool(obj, yolo):
    name = obj.get("name", "")
    try:
        if name == "read":
            with open(safe_path(obj["path"]), "r", errors="replace") as f:
                return "read " + obj["path"], trunc(f.read()), True, False
        if name == "ls":
            d = obj.get("path", ".")
            p = safe_path(d)
            items = sorted(os.listdir(p))
            out = "\n".join((i + "/") if os.path.isdir(os.path.join(p, i)) else i for i in items)
            return "ls " + d, (out or "(empty)"), True, False
        if name == "write":
            rel = obj["path"]; content = obj.get("content", "")
            if not confirm("write %s%s%s (%d bytes)" % (B, rel, X, len(content)), yolo):
                return "write " + rel, "denied by user", False, False
            p = safe_path(rel)
            os.makedirs(os.path.dirname(p) or ".", exist_ok=True)
            with open(p, "w") as f:
                f.write(content)
            return "write " + rel, "wrote %d bytes" % len(content), True, False
        if name == "edit":
            rel = obj["path"]; old = obj.get("old", ""); new = obj.get("new", "")
            if not confirm("edit %s%s%s" % (B, rel, X), yolo):
                return "edit " + rel, "denied by user", False, False
            with open(safe_path(rel), "r", errors="replace") as f:
                src = f.read()
            n = src.count(old)
            if old == "" or n == 0:
                return "edit " + rel, "old text not found — adjust and retry", False, False
            if n > 1:
                return "edit " + rel, "old text appears %d times — add more context to make it unique" % n, False, False
            with open(safe_path(rel), "w") as f:
                f.write(src.replace(old, new, 1))
            return "edit " + rel, "replaced 1 occurrence", True, False
        if name == "bash":
            cmd = obj.get("command", "")
            if not confirm("run: %s%s%s" % (B, cmd, X), yolo):
                return "bash", "denied by user", False, False
            # Stream output live so long installs (npm/expo/pip) show progress,
            # with a watchdog that kills runaway commands after BASH_TIMEOUT.
            print("\n   %s⚙%s %sbash %s%s" % (A, X, B, cmd, X))
            # start_new_session puts the shell + all its children in one process
            # group so the watchdog can kill the WHOLE tree (sleep/npm/etc.), not
            # just the shell — otherwise orphaned children keep the pipe open.
            proc = subprocess.Popen(cmd, shell=True, cwd=WORKSPACE,
                                    stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
                                    text=True, bufsize=1, start_new_session=True)
            killed = {"v": False}
            def _kill():
                killed["v"] = True
                try:
                    os.killpg(os.getpgid(proc.pid), signal.SIGKILL)
                except Exception:
                    try: proc.kill()
                    except Exception: pass
            timer = threading.Timer(BASH_TIMEOUT, _kill); timer.start()
            cap = []
            try:
                for line in proc.stdout:
                    sys.stdout.write("   %s│%s %s" % (D, X, line)); sys.stdout.flush()
                    cap.append(line)
                    if len(cap) > 400:   # keep the tail; errors usually land last
                        cap.pop(0)
            finally:
                proc.wait(); timer.cancel()
            rc = proc.returncode if proc.returncode is not None else -1
            tail = "killed: exceeded %ds" % BASH_TIMEOUT if killed["v"] else "exit %d" % rc
            ok = (rc == 0 and not killed["v"])
            print("   %s│ [%s]%s" % ((G if ok else R), tail, X))
            return "bash " + cmd, trunc(("".join(cap).strip() + "\n[%s]" % tail).strip()), ok, True
        return name, "unknown tool", False, False
    except Exception as e:
        return name, "error: %s" % e, False, False

def show_result(text):
    lines = text.splitlines() or [""]
    for ln in lines[:40]:
        print("   %s│%s %s" % (D, X, ln))
    if len(lines) > 40:
        print("   %s│ …(%d more lines)%s" % (D, len(lines) - 40, X))

def header(port, model, yolo):
    os.system("clear")
    print(A + BANNER + X)
    if port:
        print("   %s●%s %s %s· :%d%s" % (G, X, model, D, port, X))
    else:
        print("   %s●%s no tinyq4 server %s· start a model in Saient%s" % (R, X, D, X))
    mode = (Y + "yolo" + X) if yolo else (D + "confirm" + X)
    print("   %sagent%s · read ls write edit bash · %s · %s/yolo /tools /clear /exit%s" % (D, X, mode, D, X))
    print("   %scwd %s%s\n" % (D, WORKSPACE, X))

def main():
    port, model = find_server()
    yolo = False
    sys_msg = {"role": "system", "content": SYSTEM.replace("__WS__", WORKSPACE)}
    messages = [sys_msg]
    header(port, model, yolo)
    while True:
        try:
            user = input("   %s❯%s " % (A, X)).strip()
        except (EOFError, KeyboardInterrupt):
            print(); break
        if not user:
            continue
        if user in ("/exit", "/quit", "/q"):
            break
        if user in ("/clear", "/reset"):
            messages = [sys_msg]; header(port, model, yolo); continue
        if user == "/yolo":
            yolo = not yolo
            msg = "ON — tools run without asking" if yolo else "OFF — confirm writes & bash"
            print("   %syolo %s%s\n" % (Y, msg, X)); continue
        if user == "/tools":
            print("   %sread · ls · write · edit · bash%s\n" % (D, X)); continue
        if user == "/help":
            print("   %s/yolo · /tools · /clear · /exit%s\n" % (D, X)); continue
        if not port:
            port, model = find_server()
            if not port:
                print("   %sno server — load a model in Saient first%s\n" % (R, X)); continue
            header(port, model, yolo)
        messages.append({"role": "user", "content": user})
        # ── Tool loop ──────────────────────────────────────────────────────
        for _ in range(MAX_STEPS):
            print("\n   %ssaient%s  " % (A, X), end="", flush=True)
            try:
                text = stream(port, messages)
            except Exception:
                np, nm = find_server()
                if np:
                    port, model = np, nm
                    try:
                        text = stream(port, messages)
                    except Exception as e:
                        print("%serror: %s%s" % (R, e, X)); break
                else:
                    print("%sconnection lost — is a model loaded?%s" % (R, X)); port = None; break
            messages.append({"role": "assistant", "content": text})
            tool = extract_tool(text)
            if not tool:
                break  # no tool call → final answer
            label, result, ok, shown = run_tool(tool, yolo)
            if not shown:
                print("\n   %s⚙%s %s%s%s" % ((G if ok else R), X, B, label, X))
                show_result(result)
            messages.append({"role": "user", "content": "[tool result · %s]\n%s" % (label, result)})
        else:
            print("\n   %sreached step limit (%d) — type to continue%s" % (Y, MAX_STEPS, X))
        print("\n")

if __name__ == "__main__":
    main()
"####;

/// Write the Saient bash init file (and the agent TUI it launches) and return the
/// rcfile path. Returns None if $HOME is unset or the files can't be written
/// (the caller then falls back to a plain shell).
fn write_saient_rcfile() -> Option<std::path::PathBuf> {
    let home = std::env::var("HOME").ok()?;
    let dir = std::path::PathBuf::from(&home).join(".config/ai-workshop");
    std::fs::create_dir_all(&dir).ok()?;

    let cli = dir.join("saient_cli.py");
    std::fs::write(&cli, SAIENT_CLI_PY).ok()?;

    let path = dir.join("saient.bashrc");
    std::fs::write(&path, SAIENT_BASHRC).ok()?;
    Some(path)
}

// ── Tauri commands ────────────────────────────────────────────────────────────

#[tauri::command]
pub async fn pty_spawn(
    window: tauri::WebviewWindow,
    handle: tauri::State<'_, PtyHandle>,
    cwd: String,
    cols: u16,
    rows: u16,
) -> Result<(), String> {
    // Kill any existing session before spawning a new one.
    if let Some(old) = handle.lock().map_err(|e| e.to_string())?.take() {
        kill_session(old);
    }

    let shell = std::env::var("SHELL").unwrap_or_else(|_| "/bin/bash".into());

    let pty_system = native_pty_system();
    let pair = pty_system
        .openpty(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
        .map_err(|e| e.to_string())?;

    // Launch bash with our Saient init file so the `saient` command and banner are
    // available. Fall back to a plain $SHELL if bash or the rcfile is unavailable.
    let rcfile = write_saient_rcfile();
    let bash = if shell.ends_with("bash") {
        Some(shell.clone())
    } else if std::path::Path::new("/bin/bash").exists() {
        Some("/bin/bash".to_string())
    } else {
        None
    };

    let mut cmd = match (&bash, &rcfile) {
        (Some(bash_path), Some(rc)) => {
            let mut c = CommandBuilder::new(bash_path);
            c.arg("--rcfile");
            c.arg(rc);
            c.arg("-i");
            c
        }
        _ => CommandBuilder::new(&shell),
    };
    if !cwd.is_empty() && std::path::Path::new(&cwd).is_dir() {
        cmd.cwd(&cwd);
    }
    cmd.env("TERM", "xterm-256color");
    cmd.env("COLORTERM", "truecolor");

    let child = pair.slave.spawn_command(cmd).map_err(|e| e.to_string())?;
    drop(pair.slave); // close slave fd in parent — child inherited its own copy

    let mut reader = pair.master.try_clone_reader().map_err(|e| e.to_string())?;
    let     writer = pair.master.take_writer()      .map_err(|e| e.to_string())?;

    let stop      = Arc::new(AtomicBool::new(false));
    let stop_read = stop.clone();

    // Reader thread: forwards PTY output to the frontend as "pty-data" events.
    std::thread::spawn(move || {
        let mut buf = [0u8; 4096];
        loop {
            if stop_read.load(Ordering::Relaxed) { break; }
            match reader.read(&mut buf) {
                Ok(0) | Err(_) => break,
                Ok(n) => {
                    // from_utf8_lossy is fine for terminal output (ANSI + text).
                    let data = String::from_utf8_lossy(&buf[..n]).into_owned();
                    let _ = window.emit("pty-data", data);
                }
            }
        }
    });

    *handle.lock().map_err(|e| e.to_string())? = Some(PtySession {
        writer,
        master: pair.master,
        child,
        stop,
    });

    Ok(())
}

/// Write keystrokes from xterm.js into the PTY master.
#[tauri::command]
pub fn pty_write(handle: tauri::State<'_, PtyHandle>, data: String) -> Result<(), String> {
    let mut g = handle.lock().map_err(|e| e.to_string())?;
    if let Some(s) = g.as_mut() {
        s.writer.write_all(data.as_bytes()).map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Notify the kernel of a terminal resize so line-wrapping and full-screen apps stay correct.
#[tauri::command]
pub fn pty_resize(handle: tauri::State<'_, PtyHandle>, cols: u16, rows: u16) -> Result<(), String> {
    let g = handle.lock().map_err(|e| e.to_string())?;
    if let Some(s) = g.as_ref() {
        s.master
            .resize(PtySize { rows, cols, pixel_width: 0, pixel_height: 0 })
            .map_err(|e| e.to_string())?;
    }
    Ok(())
}

/// Kill the shell process and clean up the PTY session.
#[tauri::command]
pub fn pty_kill(handle: tauri::State<'_, PtyHandle>) -> Result<(), String> {
    if let Some(old) = handle.lock().map_err(|e| e.to_string())?.take() {
        kill_session(old);
    }
    Ok(())
}
